export interface Employee {
  id: number;
  matricule: string;
  cin: string;
  nom: string;
  prenom: string;
  nomComplet: string;
  telephone: string;
  email: string;
  adresse: string;
  dateNaissance: string;
  situationFamiliale: string;
  nombreEnfants: number;
  poste: string;
  departement: string;
  typeContrat: string;
  dateRecrutement: string;
  statut: string;
  actif: boolean;
  salaireBase: number;
  primesFixes: number;
  primeRendement: number;
  tarifHoraire: number;
  heuresNormalesMois: number;
  affilieCNSS: boolean;
  numeroCNSS: string;
  rib: string;
  notes: string;
  dateCreation: string;
}

export interface FichePaie {
  id: number;
  numeroBulletin: string;
  employeId: number;
  employeNom: string;
  employePrenom: string;
  employeMatricule: string;
  employePoste: string;
  employeDepartement: string;
  employeCIN: string;
  employeNumeroCNSS: string;
  employeRib: string;
  employeTypeContrat: string;
  mois: number;
  annee: number;
  periodeLabel: string;
  salaireBase: number;
  primesFixes: number;
  primeRendement: number;
  indemnites: number;
  heuresSupplementaires: number;
  tauxHoraireHS: number;
  montantHS: number;
  salaireBrut: number;
  cotisationCNSSEmploye: number;
  cotisationCNSSEmployeur: number;
  salaireImposable: number;
  avanceSalaire: number;
  autresRetenues: number;
  salaireNet: number;
  statut: 'BROUILLON' | 'VALIDE' | 'PAYE';
  datePaiement: string | null;
  notes: string;
  dateCreation: string;
}
